# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Send every request to index.html so
# react‑router can handle routing client‑side
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

